sudo: required
services:
- docker
dist: trusty
language: node_js
node_js:
- '9.1'
before_script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 
- rm -rf node_modules
- npm install
- npm run build:client-and-server-bundles
- docker build -t luiscajl/videotranscoding-frontend .
- docker push luiscajl/videotranscoding-frontend:latest
- cd nginx
- docker build -t luiscajl/videotranscoding-nginx .
- docker push luiscajl/videotranscoding-nginx:latest
script: echo "npm test temporarily disabled"



